name: Build and relase Win API

on:
 push:
   tags:
     - 'v*'

jobs:
 build:
   runs-on: windows-latest
   steps:
   - uses: actions/checkout@main

   - name: Release
     uses: softprops/action-gh-release@v2

   - name: Build
     run: |
       PATH=/clang64/bin:$PATH
       pacman -Sy --noconfirm mingw-w64-clang-x86_64-headers-git mingw-w64-clang-x86_64-tools-git zip
       mkdir build
       cd build
       widl ../Win/include/DeckLinkAPI.idl
       cp ../Win/include/DeckLinkAPIVersion.h .
       zip deck-win-api.zip *
     env:
       MSYSTEM: clang64
     shell: C:\shells\msys2bash.cmd {0}

   - name: Release
     uses: softprops/action-gh-release@v2
     if: startsWith(github.ref, 'refs/tags/')
     with:
       files: build/deck-win-api.zip
